from pandas import DataFrame


def _gen_df() -> DataFrame:
    return DataFrame(
        {
            "agA_ns": [
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
            ],
            "agA_id": [
                "6204",
                "5471",
                "31563",
                "10840",
                "3675",
                "1464",
                "9380",
                "10647",
                "2690",
                "3387",
                "10019",
                "1771",
                "2709",
                "1350",
                "9227",
                "6342",
                "11368",
                "5321",
                "21014",
                "333",
            ],
            "agA_name": [
                "JUN",
                "IGFBP2",
                "MIR193A",
                "SHC1",
                "FGF19",
                "CAMK4",
                "PRKACA",
                "CX3CL1",
                "DBI",
                "EPHA3",
                "RIPK1",
                "CDK2",
                "DCT",
                "ASZ1",
                "PPAN",
                "KIT",
                "STAT6",
                "HYAL2",
                "ANTXR1",
                "AGT",
            ],
            "agB_ns": [
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
                "HGNC",
            ],
            "agB_id": [
                "8133",
                "1667",
                "6913",
                "7809",
                "54",
                "1033",
                "6855",
                "4796",
                "10721",
                "11892",
                "4315",
                "1722",
                "6740",
                "3373",
                "1784",
                "1814",
                "5973",
                "2472",
                "16658",
                "9402",
            ],
            "agB_name": [
                "OLR1",
                "CD38",
                "MAX",
                "NGFR",
                "ABCC3",
                "BDNF",
                "MAP3K3",
                "HAAO",
                "SELP",
                "TNF",
                "GLE1",
                "CDK1",
                "LYZ",
                "EP300",
                "CDKN1A",
                "CEACAM1",
                "IL13",
                "CSRP3",
                "MOAP1",
                "PRKCG",
            ],
            "stmt_type": [
                "Activation",
                "Activation",
                "Inhibition",
                "Complex",
                "IncreaseAmount",
                "Phosphorylation",
                "Phosphorylation",
                "Activation",
                "DecreaseAmount",
                "Complex",
                "Complex",
                "Complex",
                "Complex",
                "Complex",
                "Inhibition",
                "Complex",
                "DecreaseAmount",
                "Activation",
                "Complex",
                "Activation",
            ],
            "evidence_count": [
                3,
                3,
                1,
                3,
                1,
                1,
                3,
                1,
                2,
                1,
                2,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                1,
                3,
            ],
            "stmt_hash": [
                31741960586868280,
                4663570446493643,
                -5225928615344252,
                871012315279861,
                -35661655765429541,
                22177605330108535,
                24289081904031523,
                23281261558250909,
                35776952750697286,
                -4568319726856481,
                -23458432112020946,
                4798031859825858,
                -8896943967213136,
                22418103494615766,
                -1915605860758006,
                -24574429929041166,
                -2083922954297354,
                -23129705815831640,
                9466252681718222,
                21640226596694298,
            ],
            "residue": [
                None,
                None,
                None,
                None,
                None,
                None,
                "S",
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ],
            "position": [
                None,
                None,
                None,
                None,
                None,
                None,
                "197",
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
                None,
            ],
            "source_counts": [
                {"reach": 1, "sparser": 2},
                {"reach": 3},
                {"eidos": 1},
                {"biogrid": 1, "hprd": 1, "sparser": 1},
                {"reach": 1},
                {"reach": 1},
                {"hprd": 3},
                {"reach": 1},
                {"reach": 2},
                {"sparser": 1},
                {"reach": 1, "medscan": 1},
                {"sparser": 1},
                {"sparser": 1},
                {"sparser": 1},
                {"reach": 1},
                {"sparser": 1},
                {"reach": 1},
                {"reach": 1},
                {"sparser": 1},
                {"reach": 3},
            ],
            "belief": [
                0.951,
                0.923,
                0.65,
                0.99923,
                0.65,
                0.65,
                0.989,
                0.65,
                0.86,
                0.65,
                0.8775000000000001,
                0.65,
                0.65,
                0.65,
                0.65,
                0.65,
                0.65,
                0.65,
                0.65,
                0.923,
            ],
        }
    )
